export const TipoPessoaLabels = [
  { text: "Pessoa Física", value: "FISICA" },
  { text: "Pessoa Jurídica", value: "JURIDICA" },
]

export const StatusSeguradoLabels = [
  { text: "Ativo", value: "ATIVO" },
  { text: "Inativo", value: "INATIVO" },
]

export const TipoContaLabels = [
  { text: "Corrente", value: "Corrente" },
  { text: "Poupança", value: "Poupança" },
  { text: "Salário", value: "Salário" },
]

export const EstadoCivilLabels = [
  { text: "Solteiro(a)", value: "Solteiro" },
  { text: "Casado(a)", value: "Casado" },
  { text: "Divorciado(a)", value: "Divorciado" },
  { text: "Viúvo(a)", value: "Viúvo" },
  { text: "Separado(a)", value: "Separado" },
]

export const SexoLabels = [
  { text: "Masculino", value: "Masculino" },
  { text: "Feminino", value: "Feminino" },
  { text: "Outro", value: "Outro" },
]

export const RamoPFLabels = [
  { text: "Administrador", value: "Administrador" },
  { text: "Advogado", value: "Advogado" },
  { text: "Agente Administrativo", value: "Agente Administrativo" },
  { text: "Analista Administrativo", value: "Analista Administrativo" },
  { text: "Analista de Sistemas", value: "Analista de Sistemas" },
  { text: "Assistente Administrativo", value: "Assistente Administrativo" },
  { text: "Auditor", value: "Auditor" },
  { text: "Auxiliar Administrativo", value: "Auxiliar Administrativo" },
  { text: "Atendente", value: "Atendente" },
  { text: "Caixa", value: "Caixa" },
  { text: "Comerciante", value: "Comerciante" },
  { text: "Consultor", value: "Consultor" },
  { text: "Corretor de Imóveis", value: "Corretor de Imóveis" },
  { text: "Contador", value: "Contador" },
  { text: "Designer Gráfico", value: "Designer Gráfico" },
  { text: "Desenvolvedor de Software", value: "Desenvolvedor de Software" },
  { text: "Digitador", value: "Digitador" },
  { text: "Economista", value: "Economista" },
  { text: "Empresário", value: "Empresário" },
  { text: "Estudante", value: "Estudante" },
  { text: "Farmacêutico", value: "Farmacêutico" },
  { text: "Fisioterapeuta", value: "Fisioterapeuta" },
  { text: "Fonoaudiólogo", value: "Fonoaudiólogo" },
  { text: "Gerente", value: "Gerente" },
  { text: "Jornalista", value: "Jornalista" },
  { text: "Médico", value: "Médico" },
  { text: "Motorista de Aplicativo", value: "Motorista de Aplicativo" },
  { text: "Nutricionista", value: "Nutricionista" },
  { text: "Pedagogo", value: "Pedagogo" },
  { text: "Professor", value: "Professor" },
  { text: "Psicólogo", value: "Psicólogo" },
  { text: "Publicitário", value: "Publicitário" },
  { text: "Recepcionista", value: "Recepcionista" },
  { text: "Representante Comercial", value: "Representante Comercial" },
  { text: "Secretário", value: "Secretário" },
  { text: "Servidor Público Administrativo", value: "Servidor Público Administrativo" },
  { text: "Técnico de Informática", value: "Técnico de Informática" },
  { text: "Tradutor", value: "Tradutor" },
  { text: "Vendedor", value: "Vendedor" },
  { text: "Zelador", value: "Zelador" },
  { text: "Outros (Sujeito à Análise)", value: "Outros (Sujeito à Análise)" },
]

export const RamoAtividadePJLabels = [
  { text: "Administração e Escritório", value: "Administração e Escritório" },
  { text: "Agropecuária", value: "Agropecuária" },
  { text: "Agências de Publicidade e Marketing", value: "Agências de Publicidade e Marketing" },
  { text: "Alimentação e Bebidas", value: "Alimentação e Bebidas" },
  { text: "Armazenagem e Logística", value: "Armazenagem e Logística" },
  { text: "Artes, Cultura e Entretenimento", value: "Artes, Cultura e Entretenimento" },
  { text: "Atividades Educacionais", value: "Atividades Educacionais" },
  { text: "Atividades Financeiras", value: "Atividades Financeiras" },
  { text: "Atividades Imobiliárias", value: "Atividades Imobiliárias" },
  { text: "Atividades Jurídicas", value: "Atividades Jurídicas" },
  { text: "Atividades Médicas e de Saúde", value: "Atividades Médicas e de Saúde" },
  { text: "Auditoria e Consultoria", value: "Auditoria e Consultoria" },
  { text: "Comércio Atacadista", value: "Comércio Atacadista" },
  { text: "Comércio Exterior", value: "Comércio Exterior" },
  { text: "Comércio Varejista", value: "Comércio Varejista" },
  { text: "Comunicação e Mídia", value: "Comunicação e Mídia" },
  { text: "Construção Civil", value: "Construção Civil" },
  { text: "Consultoria Empresarial", value: "Consultoria Empresarial" },
  { text: "Cooperativas", value: "Cooperativas" },
  { text: "Desenvolvimento de Software", value: "Desenvolvimento de Software" },
  { text: "Design e Comunicação Visual", value: "Design e Comunicação Visual" },
  { text: "Educação e Treinamento", value: "Educação e Treinamento" },
  { text: "Tecnologia da Informação", value: "Tecnologia da Informação" },
  { text: "Energia e Utilities", value: "Energia e Utilities" },
  { text: "Engenharia e Arquitetura", value: "Engenharia e Arquitetura" },
  { text: "Ensino Regular", value: "Ensino Regular" },
  { text: "Ensino Profissionalizante", value: "Ensino Profissionalizante" },
  { text: "Eventos e Produção Cultural", value: "Eventos e Produção Cultural" },
  { text: "Farmácias e Drogarias", value: "Farmácias e Drogarias" },
  { text: "Gestão Empresarial", value: "Gestão Empresarial" },
  { text: "Hotelaria e Turismo", value: "Hotelaria e Turismo" },
  { text: "Indústria Alimentícia", value: "Indústria Alimentícia" },
  { text: "Indústria de Transformação", value: "Indústria de Transformação" },
  { text: "Indústria Gráfica e Editorial", value: "Indústria Gráfica e Editorial" },
  { text: "Indústria Têxtil e Vestuário", value: "Indústria Têxtil e Vestuário" },
  { text: "Logística e Transporte", value: "Logística e Transporte" },
  { text: "Manutenção Predial", value: "Manutenção Predial" },
  { text: "Marketing Digital", value: "Marketing Digital" },
  { text: "Pesquisa e Desenvolvimento", value: "Pesquisa e Desenvolvimento" },
  { text: "Produção Audiovisual", value: "Produção Audiovisual" },
  { text: "Produção de Conteúdo Digital", value: "Produção de Conteúdo Digital" },
  { text: "Recursos Humanos", value: "Recursos Humanos" },
  { text: "Representação Comercial", value: "Representação Comercial" },
  { text: "Saúde e Bem-Estar", value: "Saúde e Bem-Estar" },
  { text: "Seguros e Corretagem", value: "Seguros e Corretagem" },
  { text: "Serviços Administrativos", value: "Serviços Administrativos" },
  { text: "Serviços Ambientais", value: "Serviços Ambientais" },
  { text: "Serviços de Beleza e Estética", value: "Serviços de Beleza e Estética" },
  { text: "Serviços de Limpeza e Conservação", value: "Serviços de Limpeza e Conservação" },
  { text: "Serviços de Segurança", value: "Serviços de Segurança" },
  { text: "Serviços de Tecnologia", value: "Serviços de Tecnologia" },
  { text: "Serviços Financeiros", value: "Serviços Financeiros" },
  { text: "Serviços Gerais", value: "Serviços Gerais" },
  { text: "Serviços Gráficos", value: "Serviços Gráficos" },
  { text: "Serviços de Informação", value: "Serviços de Informação" },
  { text: "Serviços de Telecomunicações", value: "Serviços de Telecomunicações" },
  { text: "Transporte de Cargas", value: "Transporte de Cargas" },
  { text: "Transporte de Passageiros", value: "Transporte de Passageiros" },
  { text: "Turismo e Agenciamento de Viagens", value: "Turismo e Agenciamento de Viagens" },
  { text: "Varejo Digital (E-commerce)", value: "Varejo Digital (E-commerce)" },
  { text: "Outros", value: "Outros" },
]
